; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; This is the base config of all examples. This config will be extended
; by each defined enviornment below (which specifies the source file that
; contains the main() function).
[env_base]
platform = ststm32
board = disco_f746ng
framework = cmsis

; Configure PIO to compile our STM library without using its automation tricks
lib_ldf_mode = off
lib_compat_mode = off
lib_deps = cube_f7_2_9_0

; Declare build flags and specify location of header files
build_flags =
  -DUSE_HAL_DRIVER
  -DSTM32F746xx
  -DUSE_STM32746G_DISCO
  -DUSE_IOEXPANDER
  -DARM_MATH_CM7
  -Ilib/cube_f7_2_9_0/Drivers/CMSIS/Include
  -Ilib/cube_f7_2_9_0/Drivers/CMSIS/Device/ST/STM32F7xx/Include
  -Ilib/cube_f7_2_9_0/Drivers/STM32F7xx_HAL_Driver/Inc
  -Ilib/cube_f7_2_9_0/Drivers/BSP/STM32746G-Discovery
  -Ilib/cube_f7_2_9_0/Drivers/BSP/Components
  -Ilib/cube_f7_2_9_0/Utilities/Fonts

; Default Environment (loop interrupt example)

[platformio]
default_envs = stm32f7_loop_intr

; Specific build environments for each example.

[env:stm32f7_adaptive]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_adaptive.c>

[env:stm32f7_average_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_average_intr.c>

[env:stm32f7_average_prbs_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_average_prbs_intr.c>

[env:stm32f7_basic_TS_synth_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_basic_TS_synth_dma.c>

[env:stm32f7_delay_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_delay_intr.c>

[env:stm32f7_dft]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dft.c>

[env:stm32f7_dftw]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dftw.c>

[env:stm32f7_dimpulse_DAC12_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dimpulse_DAC12_intr.c>

[env:stm32f7_dimpulse_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dimpulse_intr.c>

[env:stm32f7_dimpulse_recon48_FIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dimpulse_recon48_FIR_intr.c>

[env:stm32f7_dimpulse_recon48_IIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_dimpulse_recon48_IIR_intr.c>

[env:stm32f7_display]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_display.c>

[env:stm32f7_echo_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_echo_intr.c>

[env:stm32f7_fft]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fft.c>

[env:stm32f7_fft256_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fft256_dma.c>

[env:stm32f7_fft_CMSIS]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fft_CMSIS.c>

[env:stm32f7_fir_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fir_intr.c>

[env:stm32f7_fir_prbs_CMSIS_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fir_prbs_CMSIS_dma.c>

[env:stm32f7_fir_prbs_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fir_prbs_CMSIS_intr.c>

[env:stm32f7_fir_prbs_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fir_prbs_dma.c>

[env:stm32f7_fir_prbs_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_fir_prbs_intr.c>

[env:stm32f7_iirsosadapt_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_iirsosadapt_CMSIS_intr.c>

[env:stm32f7_iirsosadapt_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_iirsosadapt_intr.c>

[env:stm32f7_iirsos_delta_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_iirsos_delta_intr.c>

[env:stm32f7_iirsos_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_iirsos_intr.c>

[env:stm32f7_iirsos_prbs_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_iirsos_prbs_intr.c>

[env:stm32f7_impinviir_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_impinviir_intr.c>

[env:stm32f7_loop_buf_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_buf_dma.c>

[env:stm32f7_loop_buf_dma_v2]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_buf_dma_v2.c>

[env:stm32f7_loop_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_dma.c>

[env:stm32f7_loop_freq_resp_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_freq_resp_intr.c>

[env:stm32f7_loop_graph_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_graph_dma.c>

[env:stm32f7_loop_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_intr.c>

[env:stm32f7_loop_plot_fft_dma]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_loop_plot_fft_dma.c>

[env:stm32f7_noise_cancellation_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_noise_cancellation_CMSIS_intr.c>

[env:stm32f7_noise_cancellation_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_noise_cancellation_intr.c>

[env:stm32f7_noise_cancellation_norm_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_noise_cancellation_norm_CMSIS_intr.c>

[env:stm32f7_prbs_DAC12_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_prbs_DAC12_intr.c>

[env:stm32f7_prbs_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_prbs_intr.c>

[env:stm32f7_prbs_recon48_FIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_prbs_recon48_FIR_intr.c>

[env:stm32f7_prbs_recon48_IIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_prbs_recon48_IIR_intr.c>

[env:stm32f7_sine_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_intr.c>

[env:stm32f7_sine_lut_buf_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_lut_buf_intr.c>

[env:stm32f7_sine_lut_DAC12_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_lut_DAC12_intr.c>

[env:stm32f7_sine_lut_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_lut_intr.c>

[env:stm32f7_sine_lut_recon48_FIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_lut_recon48_FIR_intr.c>

[env:stm32f7_sine_lut_recon48_IIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sine_lut_recon48_IIR_intr.c>

[env:stm32f7_square_DAC12_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_square_DAC12_intr.c>

[env:stm32f7_square_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_square_intr.c>

[env:stm32f7_square_recon48_FIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_square_recon48_FIR_intr.c>

[env:stm32f7_square_recon48_IIR_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_square_recon48_IIR_intr.c>

[env:stm32f7_sweep_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sweep_intr.c>

[env:stm32f7_sysid_average_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sysid_average_CMSIS_intr.c>

[env:stm32f7_sysid_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sysid_CMSIS_intr.c>

[env:stm32f7_sysid_fir_CMSIS_intr]
extends = env_base
build_src_filter = +<../src/> +<../examples/stm32f7_sysid_fir_CMSIS_intr.c>