import re
from datetime import datetime
from pathlib import Path
from typing import Iterable


def write_fir_header(coeff: Iterable[float], filename: str,
                     array_name: str = 'h',
                     macro_name: str = 'N',
                     line_width: int = 6):
    """
    Generate a C header file containing float32 FIR coefficients.

    Parameters
    ----------
    coeff : Iterable[float]
        List or array of FIR coefficients.
    filename : str
        Path to the output header file.
    array_name : str, optional
        Name of the coefficient array. Default 'h'.
    macro_name : str, optional
        Name of the length macro. Default 'N'.
    line_width : int, optional
        Number of coefficients per line in the output. Default 6.

    Notes
    -----
    - Coefficients are written as float32_t in scientific notation.
    - Include guards are automatically generated from filename.
    """

    coeff = list(coeff)  # ensure we can iterate multiple times
    coeff_len = len(coeff)
    if coeff_len == 0:
        raise ValueError("Coefficient list is empty.")

    filepath = Path(filename)

    # Generate include guard from file basename
    base = filepath.stem
    guard = re.sub(r'[^A-Za-z0-9]', '_', base).upper() + "_H"

    # Generate timestamp for header comment
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open(filepath, 'w') as f:
        # Header comments
        f.write(f"// {filepath.name}\n")
        f.write("// Generated by write_fir_header.py\n")
        f.write(f"// Timestamp: {timestamp}\n\n")

        # Include guard
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")

        # Macro for coefficient length
        f.write(f"#define {macro_name} {coeff_len}\n\n")

        # Coefficient array
        f.write(f"static const float32_t {array_name}[{macro_name}] = {{\n")

        for i, c in enumerate(coeff, start=1):
            # indent start of each line
            if (i - 1) % line_width == 0:
                f.write("    ")

            # Write coefficient in scientific notation
            if i == coeff_len:
                f.write(f"{float(c): .8e}")
            else:
                f.write(f"{float(c): .8e}, ")

            # Newline after line_width coefficients or end of array
            if i % line_width == 0 or i == coeff_len:
                f.write("\n")

        # Closing brace and include guard
        f.write("};\n\n")
        f.write(f"#endif // {guard}\n")

    print(f"Successfully wrote FIR coefficients to {filepath}")