function write_iir_header(coeff, gain, filename, opts)
%WRITE_IIR_HEADER Generate a C header file for SOS IIR coefficients.
%
%   WRITE_IIR_HEADER(COEFF, GAIN, FILENAME) writes second-order
%   section (SOS) coefficients to a C header file suitable for
%   embedded DSP implementations.
%
%   COEFF must be an Mx6 matrix:
%       [b0 b1 b2 a0 a1 a2]
%   one row per section.
%
%   GAIN must be a vector of length M+1 as exported by the 
%   MATLAB FDATool. Each section numerator is scaled by GAIN(i).
%
%   Optional parameters:
%       'MacroName'     (default: 'NUM_SECTIONS')
%
%   Coefficients are written as float32_t.
%
%   UNTESTED!!!!!!!!!!!!!

    arguments
        coeff (:,6) double {mustBeFinite}
        gain (:,1) double {mustBeFinite}
        filename {mustBeTextScalar}
        opts.MacroName {mustBeTextScalar} = 'NUM_SECTIONS'
    end

    num_sections = size(coeff,1);

    if length(gain) ~= num_sections + 1
        error('GAIN must have length M+1 where COEFF is Mx6.');
    end

    fid = fopen(filename,'wt');
    if fid == -1
        error('Unable to open file: %s', filename);
    end

    cleanupObj = onCleanup(@() fclose(fid));

    % Normalize sections so a0 = 1. Should not be an issue
    % but it is good to be safe.
    for i = 1:num_sections
        if abs(coeff(i,4) - 1) > 1e-12
            coeff(i,:) = coeff(i,:) / coeff(i,4);
        end
    end

    % Include guard
    [~, base, ~] = fileparts(filename);
    guard = upper(regexprep(base, '[^A-Za-z0-9]', '_')) + "_H";

    timestamp = char(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss"));

    fprintf(fid,'// %s\n', filename);
    fprintf(fid,'// Generated by write_iir_header.m\n');
    fprintf(fid,'// Timestamp: %s\n\n', timestamp);

    fprintf(fid,'#ifndef %s\n', guard);
    fprintf(fid,'#define %s\n\n', guard);

    fprintf(fid,'#define %s %d\n\n', opts.MacroName, num_sections);

    % Numerator coefficients

    fprintf(fid,'static const float32_t b[%s][3] = {\n', opts.MacroName);
    for i = 1:num_sections
        b_scaled = single(coeff(i,1:3) * gain(i));
        if i == num_sections
            fprintf(fid,'    {% .8e, % .8e, % .8e}\n', ...
                b_scaled(1), b_scaled(2), b_scaled(3));
        else
            fprintf(fid,'    {% .8e, % .8e, % .8e},\n', ...
                b_scaled(1), b_scaled(2), b_scaled(3));
        end
    end
    fprintf(fid,'};\n\n');

    % Denominator coefficients

    fprintf(fid,'static const float32_t a[%s][3] = {\n', opts.MacroName);
    for i = 1:num_sections
        a_vals = single(coeff(i,4:6));
        if i == num_sections
            fprintf(fid,'    {% .8e, % .8e, % .8e}\n', ...
                a_vals(1), a_vals(2), a_vals(3));
        else
            fprintf(fid,'    {% .8e, % .8e, % .8e},\n', ...
                a_vals(1), a_vals(2), a_vals(3));
        end
    end
    fprintf(fid,'};\n\n');

    % Close guard
    fprintf(fid,'#endif // %s\n', guard);

    fprintf('Successfully wrote IIR SOS coefficients to %s\n', filename);
end