function write_fir_header(coeff, filename, opts)
%WRITE_FIR_HEADER Generate a C header file containing float_32 FIR coefficients.
%
%   WRITE_FIR_HEADER(COEFF, FILENAME) writes the vector COEFF to a C
%   header file specified by FILENAME. The coefficients are written as a
%   float32_t array suitable for embedded DSP applications.
%
%   WRITE_FIR_HEADER(..., Name, Value) allows additional configuration:
%
%       'ArrayName'   Name of the coefficient array (default: 'h')
%       'MacroName'   Name of the length macro (default: 'N')
%       'LineWidth'   Number of coefficients per line (default: 6)
%
%   The header file includes include guards and metadata comments.
%
%   Example
%   -------
%       b = fir1(63, 0.25);
%       write_fir_header(b, 'fir_coeffs.h', ...
%           'ArrayName', 'fir_lp', ...
%           'MacroName', 'FIR_LP_LENGTH');
%
%   Notes
%   -----
%   - Coefficients are written in float32 precision.
%   - Values are formatted in scientific notation.
%   - The function assumes the target system defines float32_t.
%

    arguments
        coeff (:,1) double {mustBeFinite}
        filename {mustBeTextScalar}
        opts.ArrayName {mustBeTextScalar} = 'h'
        opts.MacroName {mustBeTextScalar} = 'N'
        opts.LineWidth (1,1) {mustBeInteger, mustBePositive} = 6
    end

    coefflen = length(coeff);

    fid = fopen(filename, 'wt');
    if fid == -1
        error('write_fir_header:FileOpenError', ...
            'Unable to open file: %s', filename);
    end

    cleanupObj = onCleanup(@() fclose(fid));

    % Generate include guard
    [~, base, ~] = fileparts(filename);
    % RegExp sorcery
    guard = upper(regexprep(base, '[^A-Za-z0-9]', '_')) + "_H";

    timestamp = char(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss"));

    % Print header comments
    fprintf(fid, '// %s\n', filename);
    fprintf(fid, '// Generated by write_fir_header.m\n');
    fprintf(fid, '// Timestamp: %s\n\n', timestamp);

    % Print include guard
    fprintf(fid, '#ifndef %s\n', guard);
    fprintf(fid, '#define %s\n\n', guard);

    % Print macro for coefficient length (N)
    fprintf(fid, '#define %s %d\n\n', opts.MacroName, coefflen);

    % Print coefficient array
    fprintf(fid, 'static const float32_t %s[%s] = {\n', ...
        opts.ArrayName, opts.MacroName);

    % Loop through coefficients and write them to the file
    for i = 1:coefflen
        % Indent the start of each line
        if mod(i-1, opts.LineWidth) == 0
            fprintf(fid, '    ');
        end

        % Write coefficient value in scientific notation with precision
        if i == coefflen
            fprintf(fid, '% .8e', single(coeff(i)));
        else
            fprintf(fid, '% .8e, ', single(coeff(i)));
        end

        % Insert a newline after every LineWidth coefficients
        % or at the end of the array
        if mod(i, opts.LineWidth) == 0 || i == coefflen
            fprintf(fid, '\n');
        end
    end

    % Print closing brace and close include guard
    fprintf(fid, '};\n\n');
    fprintf(fid, '#endif // %s\n', guard);

    % Print success message
    fprintf('Successfully wrote FIR coefficients to %s\n', filename);
end